### ISSUE TITLE
Implement tests frameworks

### ISSUE THREAD

**Issue by zemuvier** [esikachev/project-411#39]
I think it's better to create not only unit tests, but also automation one.This project should have test framework (or frameworks), as we have already discussed. 

I need to ask: do we need UI-testing for this project (I suppose you might know "Selenium")? Or we just use some functional tests to check flask? 

Also I'm going to find better framework to create unit tests (testtols, py.test etc). Please, if you have any ideas about this, write it here.

**Comment by gaassassins** [comment]
If you wanna implement some test framework/frameworks in project then I will not mind. Whatever you are responsible for testing module. Details will discuss on our call.

**Comment by rkhozinov** [comment]
It seems that UI-testing isn't needed on that stage of the project.
I think all efforts should be concentrated around api testing.
Decompose the task and create api-tests ASAP. 
Because you already have an app in production without tests.

It seems that QA is your bottleneck, if you agree - pls restructure your process around QA.

On early stages of a development you could fix your org/flow process without any special efforts.

If you've chosen CD for shipping your code - need to satisfy all requirements.
Strict adherence to procedures reduces amount of mistakes and gives confidence in your code.

**Comment by nikitabelonogov** [comment]
ETA pls
